### ISSUE TITLE
Multiple inheritance of EMF Metaclasses leads to Python MRO exception

### ISSUE THREAD

**Issue by mn3mos** [pyecore/pyecore#89]
Hi, 

First of all, thanks for the great work! It is a nice opportunity to have something more lightweight than the eclipse framework to work with.

I encountered a problem when trying to load some existing ecore metamodels into pyecore.
Here is the exception I get:
**Resource "FunctionalAnalysis.ecore" cannot be resolved problem with "Cannot create a consistent method resolution order (MRO) for bases AbstractNamedElement, NamedElement, ExchangeSpecification"**

I have already fixed the problem of respecting order in metamodels loading. 
The raised exception **seems to stem from the fat that EMF inheritance is mapped to Python inheritance** and the fact that multiple inheritance in Python has some limitations.

For your information, i am working on loading metamodels from an existing OSS named [Capella](https://www.eclipse.org/capella/) to provide some integration tooling. 
Thus, changing the metamodel architecture is not an option to work around the MRO issue.
In addition, the metamodels are valid from an EMF perspective.

I will try to produce a minimal example producing the same output.

In the meantime, **do you know of any workaround concerning the MRO issue**?

Thanks

**Comment by aranega** [comment]
Hi @mn3mos !

Thanks a lot for the ticket, indeed, you are right, EMF multiple inheritance tree is mapped onto Python inheritance tree. This gives a support for multiple inheritance, but with some constraints. I ran into the problem in the past, but as each time, the metamodel could be modified to overcome the issue. 
Unfortunately, beside changing the metamodel, at the moment, there is no workaround... From the cases I encountered, I think I could find something so PyEcore can automatically "reorder" the inheritance tree in the metamodel so it can match the C3 linearization algorithm (only in case of an issue like this one).
I'll try to find something ASAP, in the meantime, if you have minimal examples you can propose, please do! I will use them in the tests.

Thanks!

**Comment by aranega** [comment]
@mn3mos I think I may have a patch that could work. I'm not sure yet that it covers all cases (obviously), but here is a small minimal case that fails at the moment

```python
from pyecore.ecore import EClass

A = EClass('A')
B = EClass('B', superclass=(A,))
C = EClass('C', superclass=(A, B))
```
with the patch, it works, and here is the properties that are enforced.

```python
assert C.eSuperTypes == (A, B)
assert C.python_class.__bases__ == (B.python_class, A.python_class)
```
The patch is just sorting supe classes, when an exception is raised, by number of parents in the inheritance tree. This should be ok because Ecore semantic for multiple inheritance doesn't enforce order of super classes (beside for the metamodel code generation in EMF).
It looks logical, but also it sounds too easy, I'm not sure I'm covering all cases.

**Comment by aranega** [comment]
@mn3mos I released a new version of PyEcore (`0.11.7`), that owns a fix that should be able to deal with the MRO problems. Tell me if it works for you!

**Comment by aacebedo** [comment]
Hi

I still have the MRO error when loading an metamodel with a incompatible representation in python.
I have class A,B and C
 B inherits from A
 C inherits from B and A
Python MRO resolution mechanism does not support this kind of structure.
Do you think we can tweak the lambda you added in the commit '3a5bdd4ba6c995cad43ede1c5471cf5af6f059cb' in order to  add a cleanup processing for this kind of structure before assigning the python_class attribute ?

**Comment by aranega** [comment]
Hi @aacebedo 

Thanks a lot for your comment, I was afraid that some corner cases would emerge. However, I tried quicky with your scenario in a test and it passes without any issues:

```python
def test_create_dynamic_inheritances_inconsistent2():
    A = EClass('A')
    B = EClass('B', superclass=(A,))
    C = EClass('C', superclass=(B, A))

    assert A in C.eSuperTypes
    assert B in C.eSuperTypes
    assert A.python_class in C.python_class.__bases__
    assert B.python_class in C.python_class.__bases__
```

Could you provide me the minimal `.ecore` you have that is problematic? Thanks!

**Comment by aacebedo** [comment]
Unfortunately I cannot provide the ecore.
I made my hypothesis based on this comment:  https://stackoverflow.com/a/42567588
When I tweak the Metamodel by removing those kind of relations, the ecore load succeeds.

**Comment by aranega** [comment]
ok, no problem, I'll try to produce an `.ecore` with more or less the same configuration and to see what happens. In the meantime, are you sure that you are using at least version `0.11.7`? (never hurt to ask :p)

**Comment by aacebedo** [comment]
Yes I am using the 0.11.7

I can confirm that if I clean the parent hierarchy, it works.
One thing to note is that on my eSuperTypes of C,  B is a EClass and A is a EProxy. I don't really know why and if it matters at the end.

**Comment by aranega** [comment]
Ah, the fact there is a proxy can perhaps impact the result, I'll check that asap!
Thanks a lot for the hint!

**Comment by aacebedo** [comment]
Great !
My current workaround is quite kludgy so I am open to a better stable solution.
I'll continue my experiments with more complex metamodels and models to see if the kludge is holding

**Comment by aranega** [comment]
So... I fixed the issue on `develop`... The issue was coming from the fact that I'm totally dumb... I previously patched the `EClass` creation when a hierachy is directly created, but not when one is updated (basically what happens with the XMI deserialization). Now it should work, I will try to release a version quickly, but I would like to deal with the issue #92 prior to doing the release. I will do all I can to fix #92 quickly.

**Comment by aacebedo** [comment]
Wow that was fast !
I'll try the  branch develop and keep you posted.

**Comment by aacebedo** [comment]
Unfortunately that's not working. 
When I call get_resource on resource_set go the following error
Exception has occurred: UnboundLocalError
local variable 'new_supers' referenced before assignment

ecore.py line : 807

**Comment by aacebedo** [comment]
ok here is the error:
line 807 shall be:
` new_supers = sorted(self.__compute_supertypes(),
                                    key=lambda x: len(x.eClass
                                                       .eAllSuperTypes()),`
instead of
` new_supers = sorted(new_supers,
                                    key=lambda x: len(x.eClass
                                                       .eAllSuperTypes()),
                                    reverse=True)`

**Comment by aranega** [comment]
@aacebedo Sorry about that... That's weird, the computation of the direct super types should not change if an exception occurs, `new_supers` should still be valid and `__compute_supertypes` should not raise and exception. Perhaps there is a corner case I don't cover with my test and I don't have idea how to fix. I will bother you a little bit, but could you try to move line 804 `new_supers = self.__compute_supertypes()` outside of the catch block (just on top) and tell me if it fails with your metamodel/scenario?

**Comment by aacebedo** [comment]
Yup, that's working 👍

**Comment by aranega** [comment]
Super! Thanks a lot for the test. Now I think about it... it's pretty obvious (local variable visibility in blocks), I really don't know why my tests are passing in this case... I fix and push on develop!

**Comment by aranega** [comment]
The fix for this issue is also included in the last version of the library, I hope it will be helpful to you.
